name: Sync Fork

on:
  schedule:
    - cron: '*/0 0 * * *' # every 30 minutes
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: jef
          base: main
          head: main
          auto_approve: true
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
    
